version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=referrals
    ports:
      - '5432:5432'
